### ISSUE TITLE
A52 version

### ISSUE THREAD

**Issue by HamzehTamimi** [UltraHQ/A72-Hidden-Mods#7]
Can you make a version that support Galaxy A52?

**Comment by UltraHQ** [comment]
I can't, because I don't have that device.
But if someone wants to port it (shouldn't be too hard), feel free to fork the repository.

**Comment by HamzehTamimi** [comment]
ok i will try to port it to galaxy a52 when i have the time to do that, what modifications do i need to do, like build.prop and camera-features.xml for example to make it work

**Comment by UltraHQ** [comment]
camera-features.xml, service-feature.xml and floating_feature.xml need to be adjusted
