### ISSUE TITLE
Can't install from latest 2022 may update

### ISSUE THREAD

**Issue by Rpapaa2** [UltraHQ/A72-Hidden-Mods#9]
Hello

I'm install from latest update, factory reset: okay
Sucessing install from csc mods and safety fix, install from a72 mods (latest):
Install. failed, no log.

magisk: v24.3 - zygisk, ramdisk: yes

**Comment by UltraHQ** [comment]
Hi, can you please try out the latest release again (v2.4.9) and report back, if it worked?

**Comment by Rpapaa2** [comment]
Hello.

I'm dowload to latest version and installing: failed.

Images:
https://i.imgur.com/I28gESG.jpg
https://i.imgur.com/4TcKJVS.jpg
https://i.imgur.com/yZ0602X.jpg


Any idea ?

**Comment by UltraHQ** [comment]
Okay, so I just did some more testing and found the issue.
It's GitHub. As soon as I upload and download the zip from GitHub, it does not work anymore.
The locally zipped one on my PC still works though.

I will research this issue further and provide a solution soon.

**Comment by Rpapaa2** [comment]
It's okay. Many thanks from help. :)

**Comment by UltraHQ** [comment]
So I just rechecked everything and think I found the mistake. I may have mixed up something and uploaded the wrong file.
I updated the v2.4.9 release. Can you download and test it again?

**Comment by Rpapaa2** [comment]
Success install from zip file. No problem.
Thx from help. :)

Img:
https://i.imgur.com/SaihtM7.jpg
